import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

import 'firebase_options.dart';

/// Outcome of the one-shot Firebase initialisation done in `main()`.
enum FirebaseStatus {
  /// Firebase is live; email/password sign-in works.
  ready,

  /// `firebase_options.dart` still holds placeholder values — nobody has run
  /// `flutterfire configure` for the current platform yet.
  notConfigured,

  /// Real config, but `Firebase.initializeApp` threw (bad values, no network
  /// on a cold start, misconfigured bundle id).
  failed,
}

/// Sentinel written into a checked-in placeholder `firebase_options.dart`
/// (see the repo's docs/FIREBASE_SETUP.md) so a fresh clone still builds
/// before anyone has run `flutterfire configure`. Checked against the actual
/// [FirebaseOptions] object here rather than a custom static member on
/// [DefaultFirebaseOptions] — that file is entirely regenerated by the
/// FlutterFire CLI on every run, so nothing beyond its normal generated shape
/// can live there without being silently deleted on the next `configure`.
const _placeholderMarker = 'REPLACE_WITH_FIREBASE_VALUE';

/// Initialises Firebase without ever taking the app down with it.
///
/// A farmer opening the app on a patchy connection must still reach the
/// catalogue, so a Firebase failure degrades to "authentication unavailable"
/// rather than a crash on the launch screen.
Future<FirebaseStatus> bootstrapFirebase() async {
  final FirebaseOptions options;
  try {
    options = DefaultFirebaseOptions.currentPlatform;
  } catch (error) {
    // `currentPlatform` itself throws for a platform FlutterFire was never
    // run against (e.g. this build's target has no entry yet).
    debugPrint('IrriKart: no Firebase config for this platform — $error');
    return FirebaseStatus.notConfigured;
  }

  if (options.apiKey.isEmpty || options.apiKey.contains(_placeholderMarker)) {
    debugPrint(
      'IrriKart: Firebase is not configured — run `flutterfire configure`. '
      'Sign-in is disabled; the rest of the app works.',
    );
    return FirebaseStatus.notConfigured;
  }

  try {
    if (Firebase.apps.isEmpty) {
      await Firebase.initializeApp(options: options);
    }
    return FirebaseStatus.ready;
  } catch (error, stackTrace) {
    debugPrint('IrriKart: Firebase failed to initialise — $error');
    debugPrintStack(stackTrace: stackTrace);
    return FirebaseStatus.failed;
  }
}
