// PLACEHOLDER CONFIGURATION — replace before shipping.
//
// This file is normally generated by `flutterfire configure`. It is checked in
// by hand with sentinel values so the repo builds and runs for anyone who has
// not yet been given the Firebase project. Every screen degrades gracefully
// while [DefaultFirebaseOptions.isConfigured] is false: authentication is
// disabled with a clear message rather than crashing at startup.
//
// To wire up the real project:
//
//   dart pub global activate flutterfire_cli
//   flutterfire configure --project=<firebase-project-id> \
//       --out=lib/core/firebase/firebase_options.dart \
//       --platforms=android,ios
//
// That overwrites this file. See docs/FIREBASE_SETUP.md for the full runbook.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Sentinel written into every placeholder field. `isConfigured` looks for it.
const String _placeholder = 'REPLACE_WITH_FIREBASE_VALUE';

class DefaultFirebaseOptions {
  const DefaultFirebaseOptions._();

  /// False while this file still holds the checked-in placeholders, which is
  /// what tells the app to run in "auth unavailable" mode instead of crashing.
  static bool get isConfigured =>
      !_android.apiKey.contains(_placeholder) &&
      !_android.appId.contains(_placeholder);

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
          'IrriKart does not target web — no Firebase web config exists.');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      default:
        throw UnsupportedError(
          'Firebase is not configured for $defaultTargetPlatform. '
          'Re-run `flutterfire configure` with that platform enabled.',
        );
    }
  }

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: _placeholder,
    appId: _placeholder,
    messagingSenderId: _placeholder,
    projectId: _placeholder,
    storageBucket: _placeholder,
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: _placeholder,
    appId: _placeholder,
    messagingSenderId: _placeholder,
    projectId: _placeholder,
    storageBucket: _placeholder,
    iosBundleId: 'com.irrikart.app',
  );
}
